#!/usr/bin/env python
import roslib; roslib.load_manifest('move_base_msgs')
import rospy
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from actionlib import SimpleActionClient, GoalStatus

rospy.init_node('psywerx_navigate')  
client = SimpleActionClient('move_base', MoveBaseAction)
client.wait_for_server()

goal = MoveBaseGoal()
goal.target_pose.header.frame_id = "base_link"
goal.target_pose.header.stamp = rospy.get_rostime()

goal.target_pose.pose.position.x = 1.0
goal.target_pose.pose.orientation.w = 1.0

client.send_goal(goal)
client.wait_for_result()

print client.get_state() == GoalStatus.SUCCEEDED

#rospy.spin()
