#!/usr/bin/env python
import roslib; roslib.load_manifest('sound_play')
import rospy
from zbar_ros.msg import Marker
from sound_play.libsoundplay import SoundClient

def callback(data):
    global soundhandle
    global qr_set
    if data.data in qr_set:
        soundhandle.say(data.data, 'voice_kal_diphone')
    qt_set.add(data.data)
    rospy.sleep(1)
    if len(qr_set) == 2:
        rospy.signal_shutdown('success') 
	
rospy.init_node('psywerx_qr', anonymous=True)
soundhandle = SoundClient()
qr_set = set()

rospy.sleep(1)
rospy.Subscriber('markers', Marker, callback)
rospy.spin()
